---
# file: roles/webserver/tasks/main.yml

- name: Instalando client Mysql.
  apt: name=mysql-client update_cache=yes state=latest
  tags: mysql

- name: Instalando Apache2
  apt: name=apache2 update_cache=yes state=latest
  tags: apache

- name: Abilitando modos para apache2
  apache2_module: name={{ item }} state=present
  with_items:
    - rewrite
  tags: apache

- name: Add repositorio PHP
  apt_repository: repo='ppa:ondrej/php'
  tags: php

- name: Actualizando sistema
  apt: update_cache=yes

- name: Instalando php
  apt: name={{ item }} state=latest
  with_items:
    - php5.6
    - php5.6-xml
    - php5.6-mbstring
    - php5.6-mysql
    - php5.6-mcrypt
  notify: Reiniciar Apache2
  tags: php

- name: Descargando Joomla
  get_url: url={{ joomla_dist_url }} dest="/tmp"
  tags: joomla

- name: Creando directorio Joomla
  file: path={{ joomla_install_dir }} state=directory owner=www-data group=www-data mode=0775
  tags: joomla

- name: Copiando Joomla a servidor Apache
  copy: remote_src=TRUE src="/tmp/Joomla_{{ joomla_version }}-Stable-Full_Package.zip" dest="{{ joomla_install_dir }}/Joomla.zip"
  tags: joomla

- name: Limpiando carpeta /tmp
  file: path="/tmp/Joomla_{{ joomla_version }}-Stable-Full_Package.zip" state=absent
  tags: joomla

- name: Descomprimiendo Joomla
  unarchive: copy=no src="{{ joomla_install_dir }}/Joomla.zip" dest="{{ joomla_install_dir }}" owner=www-data group=www-data mode=0775
  tags: joomla

- name: Eliminar direcotrio Instalacion Joomla
  file: path="{{ joomla_install_dir }}/installation" state=absent
  tags: joomla

- name: Importando templete configuration.php a nodo
  template: src="configuration.php" dest="/tmp" owner=www-data group=www-data mode=0775
  tags: joomla

- name: Insertando templete configuration.php a Joomla
  copy: remote_src=TRUE src="/tmp/configuration.php" dest="{{ joomla_install_dir }}"
  tags: joomla

- name: Template VHOST
  template: src={{ joomla_domain }}.conf dest="/etc/apache2/sites-available/{{ joomla_domain }}.conf"
  tags: joomla

- name: Enable VHOST
  command: a2ensite {{ joomla_domain }}.conf
  notify: Reiniciar Apache2
  tags: joomla
