---
# file: roles/database/tasks/main.yml

- name: Instalando Mysql
  apt: name=mysql-server update_cache=yes state=latest
  tags: mysql

- name: Levantando Mysql
  service: name=mysql state=started
  tags: mysql

- name: Instalando python mysql dependencias
  apt: name=python-mysqldb state=installed
  tags: mysql

- name: Cambiando credenciales user root
  mysql_user: name='root' host=localhost login_user=root login_password=root check_implicit_admin=yes
  tags: mysql

- name: Creando Base de Datos joomla
  mysql_db: name=joomla state=present
  tags: mysql

- name: Importando templete joomla.
  template: src="joomla.sql" dest="/tmp" owner=root group=root mode=0775
  tags: mysql

- name: Creando usuario Joomla
  mysql_user: name='joomla' password=joomla host=localhost login_user=joomla login_password=joomla check_implicit_admin=yes priv=joomla.*:ALL,GRANT
  tags: mysql

- name: Insertando templete joomla a mysql.
  mysql_db: name=joomla state=import target="/tmp/joomla.sql"
  notify: Reiniciar Mysql
  tags: mysql
