---
# file: roles/database/tasks/main.yml

- name: Install Mysql
  apt: name=mysql-server update_cache=yes state=latest
  tags: mysql

- name: Start Mysql
  service: name=mysql state=started
  tags: mysql

- name: Copy the my.cnf file to mysql
  template: src=my.cnf dest={{ mysql_conf_dir }}/my.cnf
  notify: Restart mysql
  tags: mysql

- name: Install python-mysql dependencies
  apt: name=python-mysqldb state=installed
  tags: mysql

- name: Changing credencials user root
  mysql_user: name='root' host=localhost login_user=root login_password=root check_implicit_admin=yes
  notify: Restart mysql
  tags: mysql

- name: Create database joomla
  mysql_db: name=joomla state=present
  notify: Restart mysql
  tags: joomla

- name: Import templete joomla
  template: src="joomla.sql" dest="/tmp" owner=root group=root mode=0775
  tags: joomla

- name: Insert templete joomla.sql to mysql.
  mysql_db: name=joomla state=import target="/tmp/joomla.sql"
  notify: Restart mysql
  tags: joomla

- name: Create user joomla to mysql
  mysql_user: name='joomla' password='1t1l2016.' host='%' login_user=joomla login_password='1t1l2016.' check_implicit_admin=yes priv='joomla.*:ALL,GRANT'
  notify: Restart mysql
  tags: joomla

- name: Clean directory /tmp
  file: path="/tmp/joomla.sql" state=absent
  tags: joomla
