---
# file: roles/dependencies/tasks/main.yml

- name: 1. Update system
  apt: update_cache=yes
  tags: update

- name: 2. Update all packages to the latest version
  apt: upgrade=dist
  tags: update

- name: 3. Install unzip
  apt: name=unzip state=present
  tags: dependency

- name: 4. Install git.
  apt: name=git state=present
  tags: git

- name: 5. Create user Sistema
  user: name=sistema comment="Alvaro Navarro" password=49056248P shell=/bin/bash group=sudo generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
  tags: tarea
